name: Common CI
on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string

jobs:
  Code-quality-Checks:
    runs-on: self-hosted
    steps:
      - name: checkout repo code
        uses: actions/checkout@v4
      - run: echo Code-Quality-Checks

  Test:
    runs-on: self-hosted
    needs: Code-quality-checks
    steps:
      - name: checkout repo code
        uses: actions/checkout@v4
      - name: Unit Tests
        run: echo Unit Tests
      - name: Integration Tests
        run: echo Integration Tests
